# Generated by Django 2.2.10 on 2020-02-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200207_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPjhjh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jhkjkiiiu', models.BigIntegerField()),
            ],
        ),
    ]
