# Generated by Django 2.2.10 on 2020-02-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bnmb', models.BigIntegerField()),
            ],
        ),
    ]
